### PR TITLE
fixed overlapping plots issue

### PR DESCRIPTION
**Pull request by enochkan**
Addresses #205 

Signed-off-by: Enoch Kan <kanxx030@gmail.com>

### CODE REVIEW

**Review by bfirsh — CHANGES_REQUESTED** [review]
Super, thank you! Same issue as #542 though -- we shouldn't be altering the behavior of the standard library.

If we can make this local to just our usage of Torch vision that would be ideal (something like https://github.com/pytorch/vision/issues/1938#issuecomment-594768546 ). But, just putting those lines in the test setup is also fine.

**Comment by enochkan** [comment]
@bfirsh done :)

**Review by bfirsh — APPROVED** [review]

**Comment by bfirsh** [comment]
Perfect. Thank you so much!

**Comment by enochkan** [comment]
No problem. I'll definitely contribute again. Happy to help.

**Review by bfirsh — CHANGES_REQUESTED** [review]
Ah -- actually there's some nuance to this bug that this fix doesn't address.

You actually want multiple plots to show up on the same graph, _if the axes are the same_.

For example, this should all display on the same plot:

```
for experiment in keepsake.experiments.all():
  experiment.plot()
```

But, if you plot a different metric, then it should display on a separate plot. Like explained in #205.

Does that make sense?

**Comment by enochkan** [comment]
Oh good call. I'll fix it right away 👍

**Comment by bfirsh** [comment]
It might be easiest to express this nuanced behavior with a test, which we should probably have anyway...

**Comment by bfirsh** [comment]
In the meantime, it'd be great to get the test fix in a separate PR though -- that is breaking the build everywhere!

**Comment by enochkan** [comment]
You mean the set_header fix is breaking the build right?

**Comment by bfirsh** [comment]
Yep. Seems like this fix might take a bit of time so it'd be great to get that spun out into a separate PR :)

**Comment by enochkan** [comment]
Most def ^^ just improved the logic so it should aggregate the same metrics now. If you want me to add testing I can work on it when I wake up hah. Brain's starting to slow down at 2am 😢 
image

**Comment by enochkan** [comment]
Added `test_plot.py` to test the nuance behavior and it is passing locally. If there is a better location for `keepsake.yaml` (or even a better way to approach for testing) please let me know. The intuition is to initialize a mock `Experiment` object using `keepsake.init` and assert the right number of plots given metrics 😄 @bfirsh @andreasjansson 

image

**Comment by bfirsh** [comment]
Amazing -- thank you! You'll need to put the experiment creation and checkpoint inside the test function though, otherwise it'll run that on import time and create that inside whatever your current directory is.

You also need to pass `temp_workdir` as an argument to the test function to create a temporary directory for your test fixtures. See `test_experiment.py` for an example.

**Comment by bfirsh** [comment]
I have also fixed the test problems in `main`, so you'll need to rebase and then the tests will work again. :)

**Comment by enochkan** [comment]
@bfirsh sorry for the messy commits (my rebase was messed up) but everything should be fixed now. Everything should be up to date with `main`. Let me know if you need me to make any changes or if it's good to merge 👍 thanks for fixing the pl test

**Comment by bfirsh** [comment]
Thanks so much for doing this quickly, @enochkan. I've cleaned this up a bit with `git rebase -i` and opened another PR with that cleaned up version: #553. This looks good so if the tests pass I'll merge it there. :)

**Comment by enochkan** [comment]
@bfirsh no worries :) and lovely. Thanks for doing this!

**Comment by bfirsh** [comment]
Merged! Thank you! ✨

**Pull request closed without merging**
